Parameters:
  env:
    Type: String
    Description: Environment
Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      AliasAttributes:
        - preferred_username
      MfaConfiguration: "OFF"
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
          TemporaryPasswordValidityDays: 3
      UserPoolAddOns:
         AdvancedSecurityMode: "OFF"
      UserPoolName: !Sub "HN_jobs_user_pool_${env}"
  UserClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      AllowedOAuthFlows:
        - implicit
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - phone
        - email
        - openid
        - aws.cognito.signin.user.admin
        - profile
      ClientName: !Sub "HN_jobs_app_client_${env}"
      ExplicitAuthFlows:
        - USER_PASSWORD_AUTH
      CallbackURLs:
        - "https://github.com/RahulHP"
      GenerateSecret: false
      RefreshTokenValidity: 30
      SupportedIdentityProviders:
        - COGNITO
      UserPoolId: !Ref UserPool
  CognitoUserPoolID:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "Cognito User Pool Client ID"
      Name: !Sub "/${env}/cognito/userpoolid"
      Type: String
      Value: !Ref UserClient