Parameters:
    env:
        Type: String
        Description: Environment
    rdsuser:
        Type: String
    rdspassword:
        Type: String
    rdsport:
        Type: Number
Resources:
  RDSDatabase:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceClass: db.t2.micro
      Engine: mysql
      EngineVersion: 5.7.22
      StorageType: gp2
      MasterUsername: !Ref rdsuser
      MasterUserPassword: !Ref rdspassword
      Port: !Ref rdsport
      PubliclyAccessible: true
      AllocatedStorage: 20
      AllowMajorVersionUpgrade: true
      AvailabilityZone: us-east-1a
      BackupRetentionPeriod: 0
  UserPostStage:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "User_Post_Stage_${env}"
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: post_id
          AttributeType: S
        - AttributeName: calendar_stage_uuid
          AttributeType: S
      BillingMode: PROVISIONED
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: post_id
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: user_calendar_stage
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: calendar_stage_uuid
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  UserLatestPosts:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "User_Latest_Post_${env}"
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: calendar_id
          AttributeType: S
      BillingMode: PROVISIONED
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: calendar_id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  UserRoleGroupID:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "User_RoleGroupID_${env}"
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      BillingMode: PROVISIONED
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  RDSHost:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "Host for RDS MySQL database"
      Name: !Sub "/${env}/rds/host"
      Type: String
      Value: !GetAtt RDSDatabase.Endpoint.Address
  RDSDBName:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "Database name for RDS MySQL database"
      Name: !Sub "/${env}/rds/db_name"
      Type: String
      Value: "hn_jobs"
  RDSPort:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "User name for RDS MySQL database"
      Name: !Sub "/${env}/rds/port"
      Type: String
      Value: !Ref rdsport
  RDSUserName:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "User name for RDS MySQL database"
      Name: !Sub "/${env}/rds/name"
      Type: String
      Value: !Ref rdsuser
  RDSUserPassword:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "User name for RDS MySQL database"
      Name: !Sub "/${env}/rds/password"
      Type: String
      Value: !Ref rdspassword
  DynamoDBUserPostStage:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "DynamoDB Table name for User Post Stage"
      Name: !Sub "/${env}/dynamodb/user_post_stage"
      Type: String
      Value: !Sub "User_Post_Stage_${env}"
  DynamoDBUserLatestPosts:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "DynamoDB Table name for User Latest Posts"
      Name: !Sub "/${env}/dynamodb/user_latest_posts"
      Type: String
      Value: !Sub "User_Latest_Post_${env}"
  DynamoDBUserRoleGroupID:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "DynamoDB Table name for User RoleGroupIDs"
      Name: !Sub "/${env}/dynamodb/user_rolegroupid"
      Type: String
      Value: !Sub "User_RoleGroupID_${env}"
Outputs:
  RDSConnectionAddress:
    Value: !GetAtt RDSDatabase.Endpoint.Address
  RDSPort:
    Value: !GetAtt RDSDatabase.Endpoint.Port