Resources:
  StepFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - states.amazonaws.com
          Action:
          - sts:AssumeRole
      Description: IAM Role to allow Step Functions to call Lambdas
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
      RoleName: HN_Step_Functions_Role
  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Description: IAM Role to allow Lambdas to use SSM
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
      RoleName: HN_Lambda_Role
  IngestingPosts:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: hackernews-jobs
        S3Key: 46ae773bd716d8575d97ca118716c0f3
      Handler: ingesting_posts.lambda_handler
      Layers:
      - arn:aws:lambda:us-east-1:290321588373:layer:LambdaLayerPython3RequestsPyMySQL:1
      Role:
        Fn::GetAtt:
        - IAMRole
        - Arn
      Runtime: python3.6
      Description: Ingesting Posts
  TransformingPosts:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: hackernews-jobs
        S3Key: 210cc47cddfe6ac42943dca7f0e961fa
      Handler: transforming_posts.lambda_handler
      Layers:
      - arn:aws:lambda:us-east-1:290321588373:layer:LambdaLayerPython3RequestsPyMySQL:1
      Role:
        Fn::GetAtt:
        - IAMRole
        - Arn
      Runtime: python3.6
      Description: Transforming Posts
  ScoringPosts:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: hackernews-jobs
        S3Key: 783b43246d2a46169f4fad243f5269c0
      Handler: scoring_posts.lambda_handler
      Layers:
      - arn:aws:lambda:us-east-1:290321588373:layer:LambdaLayerPython3RequestsPyMySQL:1
      Role:
        Fn::GetAtt:
        - IAMRole
        - Arn
      Runtime: python3.6
      Description: Scoring Posts
  StateMachine:
    Type: AWS::StepFunctions::StateMachine
    DependsOn:
    - IngestingPosts
    - TransformingPosts
    - ScoringPosts
    Properties:
      RoleArn:
        Fn::GetAtt:
        - StepFunctionRole
        - Arn
      StateMachineName: Cloud_Formation_Stack
      DefinitionString:
        Fn::Sub:
        - "{\n  \"StartAt\": \"Ingest Posts\",\n  \"States\": {\n    \"Ingest Posts\"\
          : {\n      \"Type\": \"Task\",\n      \"Resource\": \"arn:aws:states:::lambda:invoke\"\
          ,\n      \"Parameters\": {\n        \"FunctionName\": \"${IngestingPostsArn}\"\
          ,\n        \"Payload\": {\n          \"calendar_id.$\": \"$.calendar_id\"\
          \n        }\n      },\n      \"ResultPath\": null,\n      \"Next\": \"Transform\
          \ Posts\"\n    },\n    \"Transform Posts\": {\n      \"Type\": \"Task\"\
          ,\n      \"Resource\": \"arn:aws:states:::lambda:invoke\",\n      \"Parameters\"\
          : {\n        \"FunctionName\": \"${TransformingPostsArn}\",\n        \"\
          Payload\": {\n          \"calendar_id.$\": \"$.calendar_id\"\n        }\n\
          \      },\n      \"Next\": \"Pass Role Group\",\n      \"ResultPath\": null\n\
          \    },\n    \"Pass Role Group\": {\n      \"Type\": \"Pass\",\n      \"\
          Next\": \"Score Posts\",\n      \"Result\": {\n        \"role_group_id\"\
          : 1\n      },\n      \"ResultPath\": \"$.role_group_id\"\n    },\n    \"\
          Score Posts\": {\n      \"Type\": \"Task\",\n      \"Resource\": \"arn:aws:states:::lambda:invoke\"\
          ,\n      \"Parameters\": {\n        \"FunctionName\": \"${ScoringPostsArn}\"\
          ,\n        \"Payload\": {\n          \"calendar_id.$\": \"$.calendar_id\"\
          ,\n          \"role_group_id.$\": \"$.role_group_id.role_group_id\"\n  \
          \      }\n      },\n      \"End\": true\n    }\n  }\n}"
        - IngestingPostsArn:
            Fn::GetAtt:
            - IngestingPosts
            - Arn
          TransformingPostsArn:
            Fn::GetAtt:
            - TransformingPosts
            - Arn
          ScoringPostsArn:
            Fn::GetAtt:
            - ScoringPosts
            - Arn
